# Generated by Django 3.2.7 on 2021-09-19 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_events_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='isVirtual',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
