# Generated by Django 3.2.7 on 2021-09-19 00:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_events_users'),
    ]

    operations = [
        migrations.RenameField(
            model_name='events',
            old_name='users',
            new_name='participants',
        ),
    ]
