# Generated by Django 3.2.7 on 2021-09-19 01:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('project', '0005_rename_users_events_participants'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='participants',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='auth.group'),
        ),
    ]
